server:
  port: 3344

spring:
  application:
    name: cloud-config-center # 注册进Eureka服务器的微服务名
  cloud:
    config:
      server:
        git:
          uri: https://github.com/KevenPotter/springcloud-config #GitHub上面的git仓库的名字
          # 搜索目录
          search-path:
            - springcloud-config
      # 读取分支
      label: master

eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka
